#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RPM2
version:      0.63
version_from: RPM2.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
